backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "data/content.json"
        label: "Content (Cars • Success Stories • Socials)"
        name: "content"
        fields:
          - { label: "WhatsApp", name: "WHATSAPP", widget: "string", default: "+81 80 4790 9663" }
          - { label: "TikTok URL", name: "TIKTOK", widget: "string", default: "https://www.tiktok.com/@yourhandle" }
          - { label: "Brands", name: "BRANDS", widget: "list", default: ["Toyota","Honda","Nissan","Mazda","Subaru","Mitsubishi","Suzuki","Daihatsu","Isuzu","Hino","Lexus"] }
          - { label: "Categories", name: "CATEGORIES", widget: "list", default: ["Sedan","Hatchback","SUV","Truck","Van","Wagon","Coupe","Convertible","Hybrid/EV","Machinery","Agricultural"] }

          - label: "Cars (Inventory)"
            name: "cars"
            widget: "list"
            fields:
              - { label: "Image", name: "src", widget: "image", allow_multiple: false }
              - { label: "Name", name: "name", widget: "string", required: false }
              - { label: "Brand", name: "brand", widget: "string", required: false }
              - { label: "Category", name: "category", widget: "string", required: false }
              - { label: "Year", name: "year", widget: "number", required: false }

          - label: "Success Stories (Delivered)"
            name: "deliveries"
            widget: "list"
            fields:
              - { label: "Image", name: "src", widget: "image", allow_multiple: false }
              - { label: "Caption / Name", name: "name", widget: "string", required: false }
